# Generated by Django 4.1.7 on 2023-04-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='optional_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
